# ==========================================
# BASE SUBSYSTEMS
# ==========================================
CONFIG_INPUT=y
CONFIG_SPI=y

# ==========================================
# MOUSE AND SENSOR (PMW3610 ALT)
# ==========================================
CONFIG_BT_DEVICE_APPEARANCE=962
CONFIG_ZMK_POINTING=y
CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=128

# ==========================================
# SCROLL WHEEL (ENCODER)
# ==========================================
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# ==========================================
# BATTERY AND DEEP SLEEP
# ==========================================
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=120
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_ZMK_PM_SOFT_OFF=y

# ==========================================
# SWITCH DEBOUNCE (NOISE FILTER)
# ==========================================
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=20
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=20

 # ==========================================
 # POWER AND RGB UNDERGLOW LEDS
 # ==========================================

# EXT POWER - mantém VCC para o sensor
CONFIG_ZMK_EXT_POWER=y

# LEDs desabilitados para teste de bateria
CONFIG_LED_STRIP=n
CONFIG_WS2812_STRIP=n
CONFIG_ZMK_RGB_UNDERGLOW=n